<!DOCTYPE html>
<html>
    <head>
    <link type="text/css" rel="stylesheet" href="./css/style.css"/>
    <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave+Display" rel="stylesheet">
    <style>
    </style>
    </head>
    <body>
        <header>
        </header>
        <nav>
            <!-- <img style="height: 100%;" src="http://3.bp.blogspot.com/--178OLbnXkg/T-BU5KdnV8I/AAAAAAAADjo/udVCatVfjtY/s1600/www.pseffects.webs.com+(14).png"> -->
        <h1 style="font-family: 'Sedgwick Ave Display', cursive;">Silverado</h1>
        </nav>
        <main>
            <section></section>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed architecto similique, vel aut corporis omnis perferendis quas ex, porro quod, quaerat dolore perspiciatis recusandae! Illo quisquam sit, eaque, itaque facere, voluptatum ipsam optio consequatur est iure non quaerat quis corporis cum id. Animi maxime vel fuga, non deserunt culpa, nam fugiat sequi labore expedita fugit incidunt praesentium magni enim facere ducimus delectus dolor tempora minima? Impedit laudantium voluptatum architecto, aperiam cupiditate pariatur est facilis nisi numquam voluptate sint quam natus temporibus eveniet, praesentium beatae voluptates molestiae quidem neque itaque dolorum. Facere harum nemo eaque, commodi consectetur similique fuga dolorum ipsam perspiciatis ea laborum accusantium. Architecto amet, iure magni recusandae, maxime repellendus ipsa explicabo iste est suscipit nam eveniet? Asperiores dolorem doloremque, exercitationem sequi consectetur, temporibus consequatur, soluta autem pariatur labore ducimus debitis ea enim reprehenderit tempore incidunt dolores? Error, minima explicabo itaque est natus voluptatem dolores atque magni odio enim modi, numquam reprehenderit quasi sint? Autem alias illum minima atque ut porro earum inventore voluptatem incidunt, illo non accusamus ducimus molestias facilis quo est voluptates deleniti nisi in! Nesciunt vitae delectus doloremque reiciendis tenetur excepturi eum quis quae hic quod iure minima beatae tempora consequuntur laborum voluptatum facere, accusantium animi ab ea! Eius, fugit blanditiis saepe commodi ipsam modi doloremque eveniet esse deleniti quaerat obcaecati minima at voluptatibus aspernatur eligendi error porro similique id molestias ad! Obcaecati veritatis incidunt vitae aliquid dolores nesciunt reiciendis laudantium quia aut? Dicta laudantium error rerum explicabo sit iste tenetur quia doloribus, similique, nobis nemo!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate sed officia nulla. Vitae voluptates consequuntur sint. Commodi modi amet dolorum aliquam impedit porro accusamus, ullam earum vitae iure quis recusandae, voluptate nam et sed, non possimus rem. Assumenda, veritatis cumque totam ullam sit nesciunt natus, doloremque obcaecati minima sed dolor! Aspernatur obcaecati accusamus, dolorum iste qui velit assumenda, totam amet rem, exercitationem autem. Mollitia voluptatibus ab nisi maxime minima repellat? Corporis fuga labore, obcaecati impedit itaque molestias necessitatibus saepe a magni perferendis nostrum provident nisi repellendus sint, officia quam doloribus debitis accusantium nulla odio sunt! In, suscipit sapiente ipsam placeat quibusdam blanditiis dolorem rem ipsa? Eaque molestiae facilis odio voluptatibus accusamus, quidem porro delectus ducimus fuga ut nostrum reiciendis rem molestias odit velit expedita blanditiis natus officiis incidunt possimus eos necessitatibus nesciunt! Ex nulla, nesciunt nostrum reiciendis labore laboriosam est quod similique quae corrupti? Facilis sint distinctio eveniet sequi id consequatur aliquid temporibus maiores quidem earum rerum corrupti explicabo, debitis neque officiis iste obcaecati dolore magnam quasi alias ut, provident non. Fugiat sint vel quis temporibus cum ab corporis commodi praesentium delectus soluta? Consequatur dolorum dolore ipsam quia asperiores, commodi soluta, neque esse alias harum qui aperiam temporibus libero, quam sequi porro eaque? Exercitationem tenetur excepturi saepe ab accusamus incidunt. Dolor, delectus provident! Velit magni quod odit perspiciatis error? Numquam fugiat, possimus optio nostrum at magnam autem. Quaerat provident, veniam non aut quibusdam ratione? Delectus doloremque labore, quo saepe quasi obcaecati sint nemo cupiditate repudiandae quis repellendus nisi soluta facere.</p>
            <p>hello</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laudantium fugiat accusantium cum eum et mollitia! Reprehenderit quae asperiores, ducimus laboriosam ex quasi, dolores delectus deleniti cumque et beatae enim porro possimus, illo esse? Repellendus, exercitationem reiciendis fugit id possimus eum, omnis dicta quidem similique unde aut necessitatibus quae harum earum, animi consequuntur sint dolore saepe debitis sed. Nesciunt possimus voluptas iste eos sapiente aut expedita amet accusamus enim esse dolorum itaque vel molestias, at laborum dolorem fuga neque nobis sit perferendis nostrum voluptates nisi animi? Reprehenderit saepe veritatis quaerat laboriosam placeat voluptatem nisi corporis. Doloremque maxime, corrupti, dolorem eligendi impedit cumque qui ea eos, vel ducimus neque amet delectus. Officiis, laudantium voluptas earum sed debitis deserunt eum iste sapiente quidem saepe iure temporibus veritatis laborum ad mollitia iusto maxime beatae magni quibusdam ex ipsam. Sit tempore eius magnam quasi enim. Iure similique sit hic consequuntur, voluptas soluta odit saepe itaque praesentium quaerat vel ipsa cum voluptatum laudantium a unde dignissimos repudiandae incidunt. Qui quae rem explicabo autem eos, ipsam veritatis facilis magnam voluptates ex provident, dolore aspernatur dolorem. Facere aspernatur possimus velit repudiandae, autem laudantium fuga earum. Quo architecto velit animi sed nobis obcaecati soluta nam, iusto dolorem explicabo quasi porro corporis! Obcaecati, dolore iusto. Explicabo eum nihil omnis aspernatur vitae quam eos animi aperiam placeat fuga officia necessitatibus, dolorem iure, molestias debitis eius ipsum. Sapiente perspiciatis possimus enim labore accusantium soluta cumque eum? Ducimus aliquam temporibus maiores numquam iusto, perspiciatis nesciunt sed. Tempore aut cum dolore obcaecati voluptas!</p>
        </main>
        <footer>
        </footer>
    </body>
</html>